language: java

sudo: false

jdk:
    - oraclejdk8

install: mvn install -DskipTests -Dgpg.skip -Ptest

script:
    - mvn verify -Dgpg.skip -Ptest

after_success:
    - mvn coveralls:report -Dgpg.skip -Ptest

cache:
  directories:
  - $HOME/.m2
